server:
    port: 80
    tomcat:
      uri-encoding: UTF-8
      max-connections: 100
      max-threads: 100
    
spring:
    jpa:
        generate-ddl: true
        show-sql: true
        hibernate:
            ddl-auto: update
    h2:
        console:
            enabled: true
    datasource:
        url: jdbc:h2:file:./spring-blog
    jackson:
        date-format: yyyy-MM-dd'T'HH:mm:ss.SSSXXX
        time-zone : Asia/Seoul
        
    #thymeleaf start
    thymeleaf:
        mode: HTML5
        encoding: UTF-8
        servlet:
          content-type: text/html
        #开发时关闭缓存,不然没法看到实时页面
        cache: false
    #thymeleaf end

      